language: cpp

compiler:
  - gcc

branches:
  only:
    - master

before_install:
    - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - travis_retry sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - travis_retry sudo apt-get update -y

install:
    - travis_retry sudo apt-get -f install -y aptitude
    - travis_retry sudo aptitude -f install -y cmake
    - travis_retry sudo aptitude -f install -y qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
    - travis_retry sudo aptitude -f install -y qt5-default qttools5-dev-tools
    - travis_retry sudo aptitude -f install -y gcc-4.8 g++-4.8
    - travis_retry sudo apt-get -f install -y linux-libc-dev
    - travis_retry sudo aptitude -f install -y libnuma-dev

    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

notifications:
  recipients:
    - jbreitbart@gmail.com
  email:
    on_success: change
    on_failure: always

os:
  - linux