language: cpp

compiler:
  - gcc

branches:
  only:
    - master

before_install:
    - travis_retry sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - travis_retry sudo apt-get update -qq

install:
    - travis_retry sudo apt-get install -qq libqt4-dev cmake
    - travis_retry sudo apt-get install -qq gcc-4.8 g++-4.8

    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++

script:
    - ./test.sh
    - mkdir build
    - cd build
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - make

notifications:
  recipients:
    - jbreitbart@gmail.com
  email:
    on_success: change
    on_failure: always

os:
  - linux